spring:
  zipkin:
    enabled: false

management:
  security:
    enabled: false # Only for DEMO purposes

demo:
  listenerQueueName: demo-b-queue
  destinationName: demo-a-queue

logging:
  level:
    com:
      example: TRACE